export const MOCK_CATEGORIES = [
  { id: "cat-burgers", name: "Burgers Artesanais", order_index: 1 },
  { id: "cat-combos", name: "Combos (+ Batata 100g)", order_index: 2 },
  { id: "cat-super-combos", name: "Super Combos (+ Batata + Refri)", order_index: 3 },
  { id: "cat-porcoes", name: "Porções", order_index: 4 },
  { id: "cat-bebidas", name: "Bebidas", order_index: 5 },
];

export const MOCK_PRODUCTS = [
  // ================= BURGERS ARTESANAIS =================
  {
    id: "prod-classic",
    name: "CLASSIC",
    description: "Pão brioche, blend artesanal 100g, queijo cheddar fatiado, bacon crocante e molho especial da casa à sua escolha.",
    price: 23.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-smash",
    name: "SMASH 🔥 QUERIDINHO DA GALERA",
    description: "Pão brioche, 2 smash burgers de 70g (140g no total), queijo cheddar fatiado, bacon crocante e molho especial da casa à sua escolha.",
    price: 26.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: true,
  },
  {
    id: "prod-pop",
    name: "POP ⭐ ESPECIAL DA CASA",
    description: "Pão brioche, blend artesanal 160g, queijo cheddar fatiado, bacon crocante, alface americana, tomate, cebola roxa e molho especial da casa à sua escolha.",
    price: 29.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: true,
  },
  {
    id: "prod-smash-caramelizado",
    name: "SMASH CARAMELIZADO",
    description: "Pão brioche, 2 smash burgers de 70g (140g no total), queijo cheddar fatiado, bacon crocante, cebola caramelizada defumada e molho especial da casa à sua escolha.",
    price: 39.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-fit",
    name: "FIT",
    description: "Pão brioche, blend artesanal 160g, muçarela, cream cheese, ovo, alface americana, tomate e cebola roxa.",
    price: 34.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-flex",
    name: "FLEX",
    description: "Pão brioche, blend artesanal 160g, queijo cheddar fatiado, cebola crispy crocante, geleia de abacaxi com pimenta e molho especial da casa à sua escolha.",
    price: 34.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1582196016295-f8c8bd4b3a99?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-pit-stop",
    name: "PIT STOP 🏁 MAIS VENDIDO",
    description: "Pão brioche, blend artesanal 160g, queijo cheddar fatiado, bacon crocante, onion rings, alface americana, tomate, cebola roxa e molho especial da casa à sua escolha.",
    price: 34.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: true,
  },
  {
    id: "prod-v6",
    name: "V6",
    description: "Pão brioche, blend artesanal 160g, smash de 70g, queijo cheddar fatiado, bacon crocante, onion rings, alface americana, tomate, cebola roxa e molho especial da casa à sua escolha.",
    price: 37.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-nitro",
    name: "NITRO",
    description: "Pão brioche, blend artesanal 160g, queijo cheddar fatiado, bacon crocante, cream cheese, cebola caramelizada defumada, farofa de bacon e molho especial da casa à sua escolha.",
    price: 40.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-xr",
    name: "XR",
    description: "Pão brioche, blend artesanal 160g, queijo cheddar fatiado, bacon crocante, Catupiry empanado e molho especial da casa à sua escolha.",
    price: 43.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-v8",
    name: "V8 👑 320G DE CARNE",
    description: "Pão brioche, 2 blends artesanais de 160g (320g no total), queijo cheddar fatiado, bacon crocante, molho barbecue, alface americana, tomate, cebola roxa e molho especial da casa à sua escolha.",
    price: 46.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: true,
  },
  {
    id: "prod-smash-triplo",
    name: "SMASH TRIPLO 🔥 NOVIDADE",
    description: "Pão brioche, 3 smash burgers, queijo cheddar fatiado, bacon crocante, alface americana, tomate, cebola roxa e molho especial da casa à sua escolha.",
    price: 35.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: true,
  },
  {
    id: "prod-constellation",
    name: "CONSTELLATION ⭐ LANÇAMENTO",
    description: "Pão brioche, blend artesanal 160g, queijo cheddar, Catupiry empanado com costela, alface americana, tomate, cebola roxa e molho especial da casa à sua escolha.",
    price: 49.90,
    category: "cat-burgers",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: true,
  },

  // ================= PORÇÕES =================
  {
    id: "prod-porcao-batata-100g",
    name: "Batata Frita 100g",
    description: "Porção individual de 100g de batata frita sequinha e crocante.",
    price: 9.90,
    category: "cat-porcoes",
    image_url: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-porcao-batata-150g",
    name: "Batata Frita 150g",
    description: "Porção média de 150g de batata frita sequinha e crocante.",
    price: 14.90,
    category: "cat-porcoes",
    image_url: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-porcao-batata-especial",
    name: "Batata Frita 150g + Cheddar + Bacon",
    description: "150g de batata frita coberta com delicioso cheddar cremoso e cubinhos crocantes de bacon.",
    price: 20.90,
    category: "cat-porcoes",
    image_url: "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: true,
  },
  {
    id: "prod-porcao-nuggets",
    name: "Nuggets 10 un.",
    description: "10 unidades de nuggets empanados crocantes e dourados.",
    price: 16.90,
    category: "cat-porcoes",
    image_url: "https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-porcao-onion",
    name: "Anel de Cebola 12 un.",
    description: "12 unidades de anéis de cebola onion rings empanados super crocantes.",
    price: 16.90,
    category: "cat-porcoes",
    image_url: "https://images.unsplash.com/photo-1639024471285-0afc27429188?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },

  // ================= BEBIDAS =================
  {
    id: "prod-bebida-refri",
    name: "Refrigerante 350ml",
    description: "Lata 350ml gelada (Coca-Cola, Guaraná Antarctica, Fanta ou Sprite).",
    price: 7.00,
    category: "cat-bebidas",
    image_url: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-bebida-suco",
    name: "Suco Del Valle 290ml",
    description: "Lata 290ml gelada (Uva, Pêssego ou Maracujá).",
    price: 7.00,
    category: "cat-bebidas",
    image_url: "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-bebida-cerveja",
    name: "Cerveja Original 473ml",
    description: "Latão 473ml trincando de gelada.",
    price: 9.00,
    category: "cat-bebidas",
    image_url: "https://images.unsplash.com/photo-1608270192804-94b150937a4e?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-bebida-agua",
    name: "Água Mineral sem Gás 500ml",
    description: "Garrafa de água mineral 500ml gelada.",
    price: 3.00,
    category: "cat-bebidas",
    image_url: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
  {
    id: "prod-bebida-agua-gas",
    name: "Água Mineral com Gás 500ml",
    description: "Garrafa de água mineral com gás 500ml gelada.",
    price: 5.00,
    category: "cat-bebidas",
    image_url: "https://images.unsplash.com/photo-1560023907-5f339617ea30?w=600&auto=format&fit=crop&q=80",
    available: true,
    popular: false,
  },
];

export const MOCK_ADDITIONALS = [
  { id: "add-1", name: "Anel de cebola — 2 un.", price: 6.00 },
  { id: "add-2", name: "Salada", price: 2.00 },
  { id: "add-3", name: "Cheddar fatiado", price: 2.50 },
  { id: "add-4", name: "Bacon", price: 4.00 },
  { id: "add-5", name: "Geleia de abacaxi", price: 6.00 },
  { id: "add-6", name: "Smash 70g", price: 7.00 },
  { id: "add-7", name: "Carne 160g", price: 14.00 },
  { id: "add-8", name: "Catupiry empanado", price: 15.00 },
];

export const MOCK_SETTINGS = {
  restaurant_name: "Vruum Burguer",
  restaurant_logo: "",
  opening_time: "18:00",
  closing_time: "23:59",
  address: "Av. Brasil, 1500 - Centro",
  instagram: "@vrumburguer",
  whatsapp: "11999999999",
  phone: "(11) 99999-9999",
  delivery_fee: 6.50,
  min_order_value: 20.00,
  open_days: [
    { day: 0, enabled: true, open_time: "18:00", close_time: "23:59" },
    { day: 1, enabled: true, open_time: "18:00", close_time: "23:59" },
    { day: 2, enabled: true, open_time: "18:00", close_time: "23:59" },
    { day: 3, enabled: true, open_time: "18:00", close_time: "23:59" },
    { day: 4, enabled: true, open_time: "18:00", close_time: "23:59" },
    { day: 5, enabled: true, open_time: "18:00", close_time: "23:59" },
    { day: 6, enabled: true, open_time: "18:00", close_time: "23:59" },
  ],
};

export const MOCK_BANNERS = [
  {
    id: "banner-1",
    title: "Burgers Artesanais Suculentos",
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&auto=format&fit=crop&q=80",
    active: true,
    order_index: 1,
  },
  {
    id: "banner-2",
    title: "Combos Especiais com Batata e Refri",
    image_url: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=1200&auto=format&fit=crop&q=80",
    active: true,
    order_index: 2,
  },
];

export const MOCK_COUPONS = [
  {
    id: "coupon-1",
    name: "Primeira Compra",
    code: "PRIMEIRA10",
    description: "10% de desconto no seu primeiro pedido",
    discount_type: "percentage",
    discount_value: 10,
    min_order_value: 30,
    active: true,
  },
  {
    id: "coupon-2",
    name: "Desconto Burger",
    code: "VRUM5",
    description: "R$ 5,00 de desconto em pedidos acima de R$ 40",
    discount_type: "fixed",
    discount_value: 5,
    min_order_value: 40,
    active: true,
  },
];

export const MOCK_COUPON_USAGES = [];

export const MOCK_ADMIN_USERS = [
  {
    id: "admin-1",
    username: "admin",
    password: "123",
    role: "admin",
    active: true,
  },
];

export const MOCK_USERS = [];

export const MOCK_USER_ADDRESSES = [];

export const MOCK_ORDERS = [];
